wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: epoch
      6:
      - 3
    - 1: validation_loss
      5: 1
      6:
      - 1
      - 3
    - 1: position_loss
      5: 1
      6:
      - 1
      - 3
    - 1: validation_mean
      5: 1
      6:
      - 1
      - 3
    - 1: position_mean
      5: 1
      6:
      - 1
      - 3
    - 1: rollout_loss
      5: 1
      6:
      - 1
      - 3
    - 1: video
      5: 1
      6:
      - 1
      - 3
    python_version: 3.8.15
    start_time: 1673100449
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 7
      - 16
      - 24
      4: 3.8.15
      5: 0.12.16
      8:
      - 5
logging:
  desc: null
  value:
    wandb_mode: online
model:
  desc: null
  value:
    aggregation: pna
    field: world_pos
    gamma: 1
    graph_balancer:
      algorithm: none
      frequency: 1
      random:
        edge_amount: 100
      remove_edges: true
      ricci:
        loops: 150
        tau: 150
    history: false
    learning_rate: 5.0e-05
    message_passing_steps: 1
    noise: 0.003
    rmp:
      clustering: none
      connector: multiscale
      frequency: 1
      fully_connect: false
      hdbscan:
        max_cluster_size: 50
        min_cluster_size: 20
        min_samples: 1
        spotter_threshold: 0.9
      hyper_node_features: false
      hyper_noise: none
      intra_cluster_sampling:
        alpha: 0.1
        enabled: false
        spotter_threshold: 0
      num_clusters: 32
    scheduler_epoch: 10
    size: 3
random_seed:
  desc: null
  value: 0
retrain:
  desc: null
  value: true
task:
  desc: null
  value:
    batch_size: 1
    dataset: deforming_plate
    epochs: 15
    mode: all
    n_timesteps: 20
    prefetch_factor: 1
    rollout_split: valid
    task: mesh
    test:
      n_step_rollouts: 1
      n_steps: 60
      rollouts: 100
      trajectories: 100
    trajectories: 4
    validation:
      n_step_rollouts: 2
      n_steps: 10
      n_viz: 1
      rollouts: 1
      trajectories: 1
